### ISSUE TITLE
Compatibility with Necrobot 0.7.0

### ISSUE THREAD

**Issue by MyUncleSam** [nicoschmitt/necrobotvisualizer#103]
Hi there,

the visualizer is able to connect to the webservice (after switching the new property "UseWebsocket" to true.

There are following issues:
- Not displaying the position / walk paths
- Inventar, pokemons and pokeballs can not be viewed

It seems it can get one position at launch but everything else seems to be not working currently.

**Comment by EpicLPer** [comment]
Additional it cannot grab Pokestops anymore, but that's probably due to the new way they distribute those (which also broke Necrobot for a long time)

**Comment by halvors** [comment]
I am also have this exactly same issue.

**Comment by blackms** [comment]
Same.

**Comment by GraspGG** [comment]
Same here.

Walk path gets updated once after using save button within settings. Maybe that helps.

**Comment by RentonXD** [comment]
Does it work for you? my visualizer is just saying 'Connecting to the bot...' o.O

**Comment by brokenmass** [comment]
I think the issue is in the bot code , not in the visualizer

**Comment by RentonXD** [comment]
ah damn.. yea my fault sry.. ^^'

**Comment by Energex22** [comment]
Having the same problems, i can update my path by opening settings and closing again, but yet no pokemon, pokestops or anything appears...

**Comment by Molier** [comment]
any word on a compatible, working visualizer?

**Comment by TheMaskedMonkey** [comment]
By default `UseWebsocket` is set to false. (It was in the changelog) - Set it to true and the map will work again.

**Comment by plopingo** [comment]
stuck at 'Connecting to the bot...'

**Comment by Fourhundred57** [comment]
Looks like things are up and running now that NecroBot has been updated!

**Comment by TheEpTic** [comment]
Yeah, can confirm 0.7.2 fixed this.

**Comment by blackpilgrim** [comment]
I'm still stuck at "connecting to the bot" even though i already use the 0.7.2

**Comment by EpicLPer** [comment]
@blackpilgrim You need to enable the Websocket in config.json first.

**PS.: VISUALIZER WORKS WITH 0.7.2 AGAIN! ISSUE CAN BE CLOSED!**

**Comment by niicojs** [comment]
thanks all, I like when an issue resolve itself :)
