### ISSUE TITLE
only work with default port 14251

### ISSUE THREAD

**Issue by sevenzsu** [nicoschmitt/necrobotvisualizer#106]
only work with default port 14251. Cannot connect to any other port

**Comment by niicojs** [comment]
what do you mean by that?
I'm guessing you have multiple bot?

If so, If first bot config is 14251, second should at least be 2 more (14253).
Then in the visualizer, click config on lower right and put the correct port.

**Comment by xeozus** [comment]
Yes, like nicoschmitt said.

Necrobot use two listener port.
For example default is 14251, then the other port is 14252 (14251+1).

So, if you want running three app of necrobot.
You can use this necrobot setting config.ini:
- Necrobot App 1 -> "WebSocketPort": 14251
- Necrobot App 2 -> "WebSocketPort": 14253
- Necrobot App 3 -> "WebSocketPort": 14255

You can run only single app of necrobot visualizer.
then to switch bot, you can click on setting icon at bottom right corner, 
then change port of bot websocket, and click save button.

I have tried, and it is work.

**Comment by niicojs** [comment]
actually you should be able to run multple instance of the app (even if only one config is perstisted).
do you run the app through your start menu once installed?

**Comment by xeozus** [comment]
I run the app from npm start.
On my mention above, i mean.. one instance of app is more than enough for me.
Sorry, for your missunderstanding. :)

I hope you add feature to switch necrobot instance.
Like show combobox to switch, if user have multi necrobot instance.

Btw, very thanks for this great visualizer.
