### ISSUE TITLE
Change marker size on map zoom

### ISSUE THREAD

**Issue by nicdcs** [nicoschmitt/necrobotvisualizer#11]
It would be nice if the markers change their size according to the zoom level. 
So you can distinguish stuff when they're getting smaller if you zoom out.

It could be done by listening to the zoom event, and changing all markers in a layer according to it.

**Comment by Epinikion** [comment]
it does change the size, fixed i guess?!

**Comment by niicojs** [comment]
I did nothing... But honestly I kind of like how it is. I was waiting for other people to comment to see where I should go :)
