### ISSUE TITLE
Missing Number On CP, IV,

### ISSUE THREAD

**Issue by fink1018944263** [nicoschmitt/necrobotvisualizer#118]
Hi, just wondering. One of my computer shows blank on the number area, but the another one is fine and showing up the numbers. Do you know how to solve this issue or what program do I miss to install on my compyter 
![1](https://cloud.githubusercontent.com/assets/2651648/17498959/761be1b8-5d98-11e6-836e-54afeaebd627.png)
![2](https://cloud.githubusercontent.com/assets/2651648/17498958/761bab76-5d98-11e6-86cd-9d69160e8a02.png)
![3](https://cloud.githubusercontent.com/assets/2651648/17498960/761eeb74-5d98-11e6-921d-163e14bf8692.png)

**Comment by odienz** [comment]
Got this problem too. Any solution?
