### ISSUE TITLE
What does the glowing green circle mean in the pokemon list?

### ISSUE THREAD

**Issue by GoldSoulTheory1** [nicoschmitt/necrobotvisualizer#123]

**Comment by niicojs** [comment]
It mean it can be evolved. But the evolve function is not there yet :)

**Comment by GoldSoulTheory1** [comment]
@nicoschmitt Thanks bro!

Love that you added the prompt to make sure to transfer... Any way to disable it though. Sometimes I wanna do my own transfers and it was easier without the prompt. Maybe a setting I can tweak?

Love the project by the way, thanks

EDIT: nevermind, i can just click and then use enter to confirm. Also curious about what lmadlekal is asking.

**Comment by Imadlekal** [comment]
@nicoschmitt  What did you mean when you said there is "an official UI on the way" in the latest changelog ?
Necrobot developers are developing a GUI BOT as well ?

**Comment by niicojs** [comment]
yes, it seem they do. I won't spend too much time on this. The fact that they disable socket by default is a not good sign...

**Comment by VirtualDrift** [comment]
I like your GUI, clean and handy!
