### ISSUE TITLE
[request] Show skills

### ISSUE THREAD

**Issue by mo0ojava** [nicoschmitt/necrobotvisualizer#129]
Thanks for a great program! It would be great to see what skills the Pokémons have along with the current info. That piece of info is lacking when it comes to deciding which ones to transfer right away and which to keep.

**Comment by AndikaTanpaH** [comment]
@mo0ojava i just fork it.. and added Skills and other..
take a look https://github.com/andikatanpah/necrobotvisualizer (just form browser)
and report me if any error etc..

**Comment by mo0ojava** [comment]
Thanks! :)
Just installed that fork and will try it shortly.

**Comment by niicojs** [comment]
By skills you mean the /15 competencies for attack defense and he right?

**Comment by mo0ojava** [comment]
No, I'm thinking of the Quickattack and Special move respectively. These are key when deciding which pokes to keep and which to abandon. Quite handy to be able to sort out the sub par ones through the visualizer.

Tried Andikas fork with Firefox just now. For some reason the circular pokemon-button and the inventory isn't responding. Looking at the eggs works though. Mayhaps I'm doing something wrong when launching it? Just started index.html in Firefox. No Python installed. Not quite sure if that's necessary...?

**Comment by mo0ojava** [comment]
...along with att/def/stam 1-15 of course. That info would be another strength! But that's not the question above.

**Comment by AndikaTanpaH** [comment]
@mo0ojava yes.. if just click index.html its happening..
because the protocol (file:///) not allowed to read or not found.. CMIIW
maybe you should try running node (for electron) or python to start simple web server.
