### ISSUE TITLE
Pokemon Bot Visualizer connecting to the bot...

### ISSUE THREAD

**Issue by orelf12** [nicoschmitt/necrobotvisualizer#131]
Pokemon Bot Visualizer just says connecting to the bot???
"UseWebsocket" is set to true.

![screenshot 2016-08-10 14 37 58](https://cloud.githubusercontent.com/assets/20950271/17555618/20d466be-5f08-11e6-890c-a59b9da84b62.png)

**Comment by grahamracklot** [comment]
Same! Port is default and matches both sides. As well as true for websocket.

It's simple to configure, for some reason mine just aint working!

**Comment by cvpride** [comment]
try Starting the Vizualizer and then starting the Bot afterwards, worked for me

**Comment by KrustyBooga** [comment]
Same, How do I check the ports are the same and how to change websocket to true?

**Comment by KrustyBooga** [comment]
Worked it..

**Comment by Kiwaaa2** [comment]
Doesnt worked for me. 
Has someone find a other way to figure that out.
