### ISSUE TITLE
how can I know bot websocker?

### ISSUE THREAD

**Issue by bpkt119** [nicoschmitt/necrobotvisualizer#134]
anyone can help me?

**Comment by ziofat** [comment]
In NecroBOT's config folder, there is a config.json file which indicate open the socket or not and the port number for the socket.
![image](https://cloud.githubusercontent.com/assets/8521174/17577658/d92b1986-5fc3-11e6-824e-7dca7118e3db.png)

**Comment by bpkt119** [comment]
thank you so much guy

**Comment by bpkt119** [comment]
so the bot websocket in Pokemon Bot Visualizer is **wws://localhost:14251** ?

**Comment by ziofat** [comment]
That's right if you leave the port in `config.json` default.

**Comment by bpkt119** [comment]
thank you again 
I had delete its socket first, after that I can't remember it. That's why I asked.

However Thank you again
