### ISSUE TITLE
im getting a blank screen help

### ISSUE THREAD

**Issue by mrturkk** [nicoschmitt/necrobotvisualizer#135]
![aaa](https://cloud.githubusercontent.com/assets/20909623/17577778/029f8ee2-5f82-11e6-976d-506ff2b44647.jpg)

**Comment by niicojs** [comment]
Could you try launching it with command line adding --enable-logging?

**Comment by Silverous** [comment]
I'm also having the same issue except it's black. I can still mouse over where the icons are, even though I can't see it and it seems that it's still there. I can click on it too.

![capture](https://cloud.githubusercontent.com/assets/13478856/17649486/377a5df6-6269-11e6-857c-d4adf94c6b1c.PNG)
![wtf](https://cloud.githubusercontent.com/assets/13478856/17649487/3a331696-6269-11e6-892d-11a05e371fa8.PNG)

**Comment by Silverous** [comment]
It would seem I have self-solved it by simply right clicking on the Visualizer shortcut icon, going to properties, compatibility tab and then running it in windows 7 compatibility.
