### ISSUE TITLE
İts Not working on necrobot 8.5 

### ISSUE THREAD

**Issue by mucro9** [nicoschmitt/necrobotvisualizer#138]
When i start the visulazer just saying connecting bot all the time whats wrong ??

**Comment by niicojs** [comment]
did you enable web socket in config?

**Comment by mucro9** [comment]
I im did not.  Is it need That ?

**Comment by niicojs** [comment]
it is needed, yes.
in the config file it is something lije "usewebsocket: true"

**Comment by mucro9** [comment]
Oh thanx i wil do that.And ill try
