### ISSUE TITLE
Please don't stop developing this software!

### ISSUE THREAD

**Issue by NeCx** [nicoschmitt/necrobotvisualizer#140]
This is an awesome project for Necrobot. Please don't stop developing this. There some missing parts. They should be completed. All community is using this app.

Some missing features:
- Show player stats
- Display level and move sets of Pokemon
- Upgrade Pokemon
  etc.

Please don't let this great project become forlorn.

**Comment by niicojs** [comment]
Honestly Necro disabled websocket by default which is needed for this to work. I say this is a prety good indication that I should not spend too much time on it.

**Comment by sir1ke** [comment]
necro disabled their whole project, so i doubt there will be anything coming gui related soon. Maybe team up with another bot dev, to get your visuliser integrated into the bot packages? ;)

**Comment by NeCx** [comment]
https://github.com/NoxxDev/NecroBot
@nicoschmitt This guy is trying to update the tool. Maybe work with him?
https://github.com/PocketMobsters/MobBotTemp
This guys also continue their work.

**Comment by NeCx** [comment]
https://github.com/NoxxDev/NecroBot
@nicoschmitt This guy is trying to update the tool. Maybe work with him?
https://github.com/PocketMobsters/MobBotTemp
These guys also continue their work.

**Comment by Yanik39** [comment]
Yep, while necro bot is dead i am using mobbot. and with their latest version their cli stops after connection to your gui.
So it would be nice to realease at least 1 more version :D..

**Comment by vfuyong** [comment]
The open source community never die..something is coming up :) This project should never die...
necro web socket feature will be inherited by new development, you dont have to worry @nicoschmitt

**Comment by vfuyong** [comment]
@nicoschmitt  Check this out:
https://github.com/NoxxDev/NecroBot

**Comment by ridetheflatline** [comment]
@nicoschmitt This software of yours right here is kick-ass dude... and Necro has picked off where it was left and is still heavily used. Fingers crossed that you keep progressing with this software.

**Comment by AndikaTanpaH** [comment]
all i just improved the visualizer, check https://github.com/AndikaTanpaH/NecrobotJavanHawk
i'll see https://github.com/NoxxDev/NecroBot

**Comment by hardknoxni69a** [comment]
Absolutely amazing definitely dont stoo developing and @noxxdev is going hard theyve had almost million downloads in last 2 weeks so necromonicon may b dead but necrobot is far from and if you guys incorporated and made it visible the moves and you could prob help with the config gui you guys would dominate the bot market even more than you already do
