### ISSUE TITLE
Stays at "Connecting to the bot..."

### ISSUE THREAD

**Issue by ahmetb** [nicoschmitt/necrobotvisualizer#142]
Even though the port numbers are matching and the bot is running, I can't get it to work.

I'm using 1.0.8 from unextracted `NecrobotVisualizer-1.0.8-win.zip`.

> ![image](https://cloud.githubusercontent.com/assets/159209/17613421/ecbd69f6-6011-11e6-9134-9c01a9323d08.png)

**Comment by MrMime71** [comment]
set use websocks in necrobot config to true. its false by default.
  "UseWebsocket": true,
  "WebSocketPort": 14251,

**Comment by ahmetb** [comment]
@MrMime71 oh wow this was it thanks, not sure why they ship it as disabled by default...

**Comment by JakeCube** [comment]
i been set 
"UseWebsocket": true,
"WebSocketPort": 14251,
between necro + visualizer still connecting...
im using 0.8.5 is it 1.8 not compatible on the version?
