### ISSUE TITLE
View bot on another pc (same LAN)

### ISSUE THREAD

**Issue by vcxy** [nicoschmitt/necrobotvisualizer#144]
My bot is running on another pc in same LAN. Can I view the Bot on the another PC? I've testet with setting Websocket to: wss://192.168.0.5:14251  but it shows only "connectiong to the bot"

**Comment by niicojs** [comment]
Should work

**Comment by vcxy** [comment]
It don't work for me.
With the tool "port Ping" I can ping the remote port 14251 (Port is open). Can anyone confirm that this works?

**Comment by ShadXo** [comment]
I tried it and its working fine, there are problems running it from a network drive, giving the same error.

**Comment by vcxy** [comment]
@ShadXo thanks for testing!
My bot was running on a MS Vista PC till yesterday and that's the reason why I intended to view it from another PC. 
Now I use my bot on a old Windows 7 Notebook and viewing from another Win7 PC works fine now.
