### ISSUE TITLE
Launch the program and you see 

### ISSUE THREAD

**Issue by raffybest94V01** [nicoschmitt/necrobotvisualizer#150]
pity that the program does not work despite the door is the same does not connect to any bot

**Comment by WORMSS** [comment]
I am running it right now, I am guessing there must be something configured on your machine (possibly firewall, or your bot's config) that is preventing you from connecting to the bot?

**Comment by raffybest94V01** [comment]
pokemob work necrobot not work.

**Comment by WORMSS** [comment]
necrobot by default disables Websocket.
I am not sure how to enable/disable on necrobot, but they may have something about turning it on, on their wiki

Only thing I can find about it on pokemob is the actual port itself.

```
"WebSocketPort": 14251,
```

**Comment by raffybest94V01** [comment]
necrobot have 

"UseWebsocket": false,
 "WebSocketPort": 14251,

**Comment by WORMSS** [comment]
So if you turn `"UseWebsocket": false,` into `true` does the visualizer start working?

**Comment by Rukeith** [comment]
I use the `npm start` and it also show up `Can't connect to bot`

**Comment by WORMSS** [comment]
... I am not sure what `npm start` has to do with this.. but ok, good for you ...

@Rukeith 
Which bot are you running? Necro or Mobbot?
If Nerco, is `"UseWebsocket"` present and set to `true`

Which WebSocketPort is your configs set to? (Yes, both visualizer and the bot).
