### ISSUE TITLE
Opening menus while connected to Mobbot has lead to 3 bans so far.

### ISSUE THREAD

**Issue by Rannilas** [nicoschmitt/necrobotvisualizer#153]
Opening either the inventory list or the pokemon list produces a red text error in the newest version of Mobbot.

This is the error when opening the pokemon list:
[22:44:37] Unexpected character encountered while parsing value: P. Path '', line 0, position 0.

This is the error when opeing the item inventory:
[22:45:08] Error parsing Infinity value. Path '', line 1, position 2.
{Line 1, position 2 is the infinity symbol for the standard incubator.}

We all experience perma-bans within minutes of these errors popping up.  Sniping was not involved.  Just running Mobbot with modest and slow settings.  It may be a coincidence, but we wanted to spare anyone else the pain of banning by sharing our observation with you.

**Comment by WORMSS** [comment]
I'm guessing your config is being a little too aggressive. And that was the reason for the ban. I was working on modifying some stuff in the inventory part of the code yesterday and was needing to open it over and over and over again, all the time reporting that error in the bot. 

No ban here.

**Comment by starcrafted** [comment]
No ban here either, opened the inventory and other buttons of the visualizer, no ban yet whatsoever.
