### ISSUE TITLE
[NOT RUN] Visualizer can not run with Necrobot 0.9.3

### ISSUE THREAD

**Issue by iwean** [nicoschmitt/necrobotvisualizer#157]

**Comment by PoopDingles** [comment]
I'm using it with 0.9.3, no issues.

**Comment by crisperfx** [comment]
@iwean can you provide more information about the error you get in to?

**Comment by ausscheider** [comment]
@iwean 

in necrobot config:

},
"WebsocketsSettings": {
"UseWebsocket": true,
"WebSocketPort": 14253

and then in necrobotvisualizer
Bot WebSocket
wss://localhost:14253

**Comment by iwean** [comment]
@ausscheider Ok, it's work now. Thx.
