### ISSUE TITLE
Can anyonce teach me how to view? 

### ISSUE THREAD

**Issue by helpmeplease1** [nicoschmitt/necrobotvisualizer#158]
I am using NecroBot Forked v0.9.4. I just save and open the software but the screen show connecting but nothing happen. Please help. Nacro bot socket is set true and socket no also correct.

**Comment by ausscheider** [comment]
@helpmeplease1 

in necrobot config:

  },
  "WebsocketsSettings": {
    "UseWebsocket": true,
    "WebSocketPort": 14253

and then in necrobotvisualizer
Bot WebSocket
wss://localhost:14253

**Comment by psydex** [comment]
@ausscheider it didn't work for me that way
![screenshot_1](https://cloud.githubusercontent.com/assets/5594251/18380572/a18016fc-7680-11e6-97ab-46e1537e3230.png)

EDIT: Nvm it worked! I had to restart both and allow network communication for Necrobot.
Thank you
