### ISSUE TITLE
inventory management not working? v1.0.9

### ISSUE THREAD

**Issue by popsoda27** [nicoschmitt/necrobotvisualizer#159]
managing of items in inventory not working as featured, e.g. deleting of potions. After setting the amount of potions to drop, after clicking ok, the correct amount of potions are removed but when refreshing the items page either by clicking the refresh button or reopening it, the deleted items are still there.

**Comment by niicojs** [comment]
True. The part in the visualizer is done, but not the part in the bot.

**Comment by popsoda27** [comment]
oh i see. so there's need for additional coding in the bot to communicate with this feature. im sorry i have no idea of this but really thank you for the good work. i guess i should bring it up to the bot dev instead? or has it already been communicated?

**Comment by niicojs** [comment]
I've just submitted a PR to the bot. Once accepted, you'll have to update the bot and it should work.

**Comment by niicojs** [comment]
Closing for now, reopen if you have issue.
