### ISSUE TITLE
my eggs count is wrong

### ISSUE THREAD

**Issue by akkarapon** [nicoschmitt/necrobotvisualizer#160]
![image](https://cloud.githubusercontent.com/assets/275038/17882625/b0af13f4-6937-11e6-8993-643b77d5892f.png)

i have 9 eggs, but shown 12/9

**Comment by niicojs** [comment]
Thanks. I'll try to understand why but it currently does not happend with my test account.

**Comment by niicojs** [comment]
if you can test it again with latest version (1.1.0)

**Comment by akkarapon** [comment]
thanks. 
now at version 1.1.0, it's ok.
