### ISSUE TITLE
Button "Go"

### ISSUE THREAD

**Issue by pedromig123** [nicoschmitt/necrobotvisualizer#161]
Hello, when I click on that "[GO](http://puu.sh/qMAmM/8d813b179b.png)" button, the character doesn't change trajectory and  appears in the console [#img](http://puu.sh/qMBDe/ec6244cc8f.png). Is it normal or has it not yet been implemented?

**Comment by niicojs** [comment]
Yes, sorry about that, not implemented for Necrobot.

**Comment by pedromig123** [comment]
but it will be implemented later? if not, where i can download mobbot? https://github.com/PocketMobsters/MobBotTemp is disabled for me.

**Comment by niicojs** [comment]
This is not planned (at least not by me) on neither Necrobot ofr Mobbot.
It commes from another project of mine, sorry.
