### ISSUE TITLE
IT Translation

### ISSUE THREAD

**Issue by aetherstrata** [nicoschmitt/necrobotvisualizer#163]
I'd like to translate this in italian.
Where are the translation files? ;)

**Comment by niicojs** [comment]
Hi.
The app itself cannot be translated at the moment, there isn't much text anyway.
However, iventory and pokemon names can be, look at here: https://github.com/nicoschmitt/necrobotvisualizer/tree/master/app/assets/json

**Comment by deframet** [comment]
Thank you :)
