### ISSUE TITLE
[REQUEST] Save pokestop locations for later use

### ISSUE THREAD

**Issue by nse7ens** [nicoschmitt/necrobotvisualizer#165]
When walking around, you can see the nearby pokestops appearing on the map.
However, when clearing the map, or re-opening the application, all previously "found" pokestops are gone again.
I think it would be very useful if this data was saved and reloaded when reopening the application. This would mean a great resource for GPX creation.

**Comment by REDESTOR** [comment]
use this... it has the location of every pokestop and gym over the world... https://www.ingress.com/intel
