### ISSUE TITLE
[NOT RUN] Visualizer can not run with new realese Necrobot 0.9.6

### ISSUE THREAD

**Issue by iwean** [nicoschmitt/necrobotvisualizer#166]
Help please.... have done with websocket and port.... but nothing happend.

For new release NecroBot 9.6

**Comment by niicojs** [comment]
Should work fine, make sure config is correct between the bot and the visualizer.
In the visualizer, make sure config looks like `wss://localhost:8000` where 8000 is the port defined in NecroBot.
(obviously, choose any port you want)

**Comment by iwean** [comment]
@nicoschmitt I'm already set it.... but still not work.

  "WebsocketsConfig": {
    "UseWebsocket": true,
    "WebSocketPort": 14251
  },

`wss://localhost:14521`

**Comment by iwean** [comment]
Btw @nicoschmitt are you have tested the new realese 9.6 ?

**Comment by ghost** [comment]
@iwean 
working in v0.9.6

**Comment by niicojs** [comment]
You misspelled the port. 14251 vs 14521.

**Comment by iwean** [comment]
OMG ...... my mistake. Sorry everybody.... misspelled.
