### ISSUE TITLE
Inventory items names

### ISSUE THREAD

**Issue by niicojs** [nicoschmitt/necrobotvisualizer#17]
I need help finding the real name of inventory items in each language

**Comment by Oolaruu** [comment]
French,
1: "Poké ball",  --->  1: "Poké Ball",
1001: "Pokemon Storage Upgrade",  ---> Extension du stockage de pokémon
http://prntscr.com/bzlipq
 1002: "Item Storage Upgrade" ---> Agrandir le sac   or   Extension du stockage des objets

**Comment by ghost** [comment]
Do you want to setup an ItemID -> Translation file?

`"TranslationStrings": [
    {
      "Key": "pokeball",
      "Value": "Pokéball"
    },
    {
      "Key": "greatPokeball",
      "Value": "Superball"
    },
    {
      "Key": "ultraPokeball",
      "Value": "Hyperball"
    },
    {
      "Key": "masterPokeball",
      "Value": "Meisterball"
    },`
Can't you just pull names from translation._language_.json for the proper language? Should be the first 4 entries in that json file.

**Comment by niicojs** [comment]
Thanks @Oolaruu .
@Afraidium : it is here https://github.com/nicoschmitt/necrobotvisualizer/tree/master/app/assets/json

**Comment by redongreen** [comment]
nico are you active in any discord channels?

**Comment by niicojs** [comment]
yes as niico
