### ISSUE TITLE
Incorrect display of Incubator distance.

### ISSUE THREAD

**Issue by ghost** [nicoschmitt/necrobotvisualizer#19]
Current incubator stats are incorrect.
[Image](https://i.gyazo.com/ceee1fd9126f373b09827111049373cc.png)

Maybe this is just template result until implemented?

**Comment by niicojs** [comment]
It is implemented and I don't see it that way.
Quick question: on your phone, you have km or mile ?

**Comment by niicojs** [comment]
I think I found it. Anybody wants to test from source to see if it is corrected?
