### ISSUE TITLE
clicking cancel in settings resets bot connection

### ISSUE THREAD

**Issue by timelf123** [nicoschmitt/necrobotvisualizer#2]

**Comment by niicojs** [comment]
true, this would need quite some work as main screen and settings are basically two different javascript app. browsing from one to the other loose all context.
I'll think about it.

**Comment by niicojs** [comment]
may be easier than I thought, try to get fix for next version

**Comment by niicojs** [comment]
I've uploaded a 1.0.1 release, tell me if it correct the issue

**Comment by timelf123** [comment]
Thanks!
