### ISSUE TITLE
Does not work well with PokéMobBot

### ISSUE THREAD

**Issue by IniTW8X** [nicoschmitt/necrobotvisualizer#20]
Snipe success messages are appearing, but map is stuck at "Waiting for GPS coords from bot..."

**Comment by niicojs** [comment]
Could you tell me wich version you are using?
On both bot side and visualizer side.

(works on my machine)

**Comment by IniTW8X** [comment]
After this pull, everything works fine with the latest version - https://github.com/PocketMobsters/PokeMobBot/pull/29

**Comment by niicojs** [comment]
yes, all this shit made features get lost on the way.
Now that necro is back again I really don't know how things will evolve...
