### ISSUE TITLE
pokemon catch escape

### ISSUE THREAD

**Issue by health901** [nicoschmitt/necrobotvisualizer#21]
When the pokemon escaped, the windows shows snipe success alert multi times  and add several icons at the same place

with PokemobBot 0.5.0

**Comment by niicojs** [comment]
on the bot side did it display it correctly? could you send me the log of the bot?

**Comment by niicojs** [comment]
Ok I think I see it now.
It seems to be a bug on the bot but I think I have a workaround. 
Could you try running the latest source of the visualizer to test it ?

If not, you can wait for the next release.
