### ISSUE TITLE
1.4 bottom right buttons issue

### ISSUE THREAD

**Issue by DerekCL** [nicoschmitt/necrobotvisualizer#22]
Hello,

I'm currently running NecrobotVisualizer.Setup.1.0.4 and the buttons in the right hand corner are causing issues.

The following buttons have no effect:
show pokemon
show eggs
show inventory.

**Comment by niicojs** [comment]
which version of the bot are you using ?

**Comment by DerekCL** [comment]
currently using the SniperBuild 30 July
which contains the 
NecroBot
SnipeBot

**Comment by niicojs** [comment]
could you link to this version? As I'm modifying the bot itself as I add features the bot has to be up to date.

**Comment by DerekCL** [comment]
https://github.com/NecronomiconCoding/NecroBot (NecroBot)

**Comment by DerekCL** [comment]
There is also https://github.com/5andr0/PogoLocationFeeder (SnipeBot)

**Comment by DerekCL** [comment]
As I test this with the PokeMobBot (https://github.com/PocketMobsters/PokeMobBot) as well as the SnipeBot it seems to have all the buttons but inventory working.

**Comment by niicojs** [comment]
do you use a precompiled version or the source ?
I guess the precompiled version does not contains the required fix.
The source should work fine.

**Comment by DerekCL** [comment]
I downloaded everything from Github but it seems like NecroBot will no longer be supported so I will use PokeMobBot and SnipeBot from now on. That configuration only has the inventory not working.

**Comment by niicojs** [comment]
There are both supposed to be supported.
In fact the latest features in the source (transfer pokemon from UI) works only on Necro as there are more willing to accept PR.
