### ISSUE TITLE
Follow Player on map does not save

### ISSUE THREAD

**Issue by rygos** [nicoschmitt/necrobotvisualizer#26]
If i save the Setting for "Follow player on map" it does not work.

I Use the newest Source of Visualizer and Necro

**Comment by niicojs** [comment]
Yes, known issue. Just wait 10 minutes for a new release.

**Comment by rygos** [comment]
This issue is not solved. =/ I'm using 1.0.5 Release

**Comment by niicojs** [comment]
It is fixed in the source tree, will be in next release

**Comment by niicojs** [comment]
I missed 1.0.5 sorry
