### ISSUE TITLE
Start does not work - Win 10

### ISSUE THREAD

**Issue by sir1ke** [nicoschmitt/necrobotvisualizer#27]
Im running a win10 32bit maschine.
Anything more you need to know? :/
[SquirrelSetup.txt](https://github.com/nicoschmitt/necrobotvisualizer/files/392648/SquirrelSetup.txt)

**Comment by niicojs** [comment]
Could you te if you're using a 64bits OS?
https://support.microsoft.com/en-us/kb/827218

**Comment by rickerd** [comment]
I have the same. I'm using a 32 bits Windows 10.

**Comment by sir1ke** [comment]
I have no 64bit compatible computer...

**Comment by niicojs** [comment]
Next release I'll upload a 32 bits version, as well as a zip version.
