### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by aronprins** [nicoschmitt/necrobotvisualizer#28]
Installer not completing :(

The version of this file is not compatible with the version of Windows (7) you're running.

Something regarding by 32/64 bit install?
Perhaps you can release two versions :)?

Thanks!

**Comment by niicojs** [comment]
The only avaiable version is 64bits for now.
I'l add this on my todo ist.

**Comment by niicojs** [comment]
Try latest version and tell me.
