### ISSUE TITLE
Sugestion Sort by Pokemon #

### ISSUE THREAD

**Issue by howcanihelp** [nicoschmitt/necrobotvisualizer#34]
Maybe it would be possible to sort the pokemon by its #? It would be a lot easier to compare the ones of the same kind.

**Comment by niicojs** [comment]
Good idea.

**Comment by howcanihelp** [comment]
Terrific Job you're doing there, nicoschmitt!

I just checked your recent version both x64 and x32 (exe version) and the new function Sort by # is not properly working.
Maybe it's getting the pokemon unique number instead of its pokedex number. (or maybe it's me)
I tried with both NecroBot and PokeMobBot

keep up the great work!

**Comment by niicojs** [comment]
yes I know sorry. it's indeed sorted by unique name. correct in source.
