### ISSUE TITLE
Configfile & Websocket

### ISSUE THREAD

**Issue by Gripexus** [nicoschmitt/necrobotvisualizer#35]
i really dont understand the "Wiki"! What is the right config file? And where i get this websocket url and port?

**Comment by niicojs** [comment]
if you don't change anything the default will work.

wss://[computer]:[port]

computer is the name or ip the your computer (localhost for current pc), port is the port you defined in the bot config file.

**Comment by Gripexus** [comment]
I opened "config" and put "wss://IPOFMYCOMPUTER:14251" and pressed "save" - nothing happens and if i open "index" the bot just wait for GPS coordinates.

**Comment by niicojs** [comment]
Which bot are you using ? necro or mobbot ? 
Which version ? Compiled or from the source ?

(not if the bot and the UI are on the same computer you can just leave default settings)

**Comment by Gripexus** [comment]
Necrobot - Newest Version (0.5.0?)

Compiled

Bot and UI is both using with my Laptop

**Comment by niicojs** [comment]
does it work better with all new release?

**Comment by Gripexus** [comment]
Yes!!! Works like a charm! Thanks!!!!
