### ISSUE TITLE
Egg is not displaying

### ISSUE THREAD

**Issue by N3evin** [nicoschmitt/necrobotvisualizer#36]
When i clicked on egg, there is no pop up. Using 1.0.5

**Comment by niicojs** [comment]
Which bot are you using ? necro or mobbot ? 
Which version ? Compiled or from the source ?

**Comment by N3evin** [comment]
Using necro latest and from source.

**Comment by N3evin** [comment]
Ops I mean it's necro latest and is already compiled.

**Comment by N3evin** [comment]
More information: using latest necrobot from their released, which is already compiled v1.0.1 and using the visualizer from the latest released that is already compiled in release.

**Comment by niicojs** [comment]
1.0.1 so you mean PokeMobBot and not NecroBot right?
NecroBot latest source works so you may have to wait a bit.
For MobBot, I'll have to check.

**Comment by N3evin** [comment]
My bad it's NecroBot v0.5.0. Was looking at the wrong git. Yeah saw v0.5.0 on my log.

[19:46:25](UPDATE) Perfect! You already have the newest Version 0.5.0

I am using visualizer V1.0.5, when i clicked on the egg, there is no pop up

**Comment by N3evin** [comment]
There is no notification and the map does not follow players, even thou i saved the setting in settings. When i open settings again, it became untick.

**Comment by niicojs** [comment]
indeed, there seem to be an issue with the option

**Comment by li81** [comment]
I am using the same stuff, but the eggs are working fine.

**Comment by N3evin** [comment]
I'm on window 10. If that's help for more information.

**Comment by li81** [comment]
Same, windows 10, 64bit.

**Comment by N3evin** [comment]
Weird, have no idea what's wrong with it then.

**Comment by niicojs** [comment]
It may be a version issue on the bot side. If you compile the bot yourself it will probably work.

**Comment by Epinikion** [comment]
Have the same from time to time, seems to be an error on necrobot side while its in an loop stage or something... most likely after starting the visualizer

**Comment by niicojs** [comment]
Yes when the bot is starting for some time communication is buggy. Once launched it should be ok.
