### ISSUE TITLE
Transfer doesn't work

### ISSUE THREAD

**Issue by tplk** [nicoschmitt/necrobotvisualizer#39]
Using v1.0.6, After clicking on trash can icon pokemon fades away from the list but isn't transferred and appears again after refresh.

**Comment by niicojs** [comment]
it's probably because it has not been implemented on the bot you are using. only necrobot run from source code as of today

**Comment by Epinikion** [comment]
It works fine with my last build of necrobot (and nicos pullrequest) from 3hrs ago. So, no bug :)

**Comment by degree8th** [comment]
Using  v1.0.6 + necro 0.5 released in 20 hours ago  the transfer is not working.

**Comment by tplk** [comment]
> Using v1.0.6 + necro 0.5 released in 20 hours ago the transfer is not working.

Yeah.
Ok. Will wait till new version is released.

**Comment by li81** [comment]
Using v1.0.6 + necro 0.5 released in 20 hours ago the transfer is not working.

Confirmed.

**Comment by niicojs** [comment]
Wait for a release or build the bot from the source. Closing.
