### ISSUE TITLE
Make it possible to start multiple instances

### ISSUE THREAD

**Issue by agp89** [nicoschmitt/necrobotvisualizer#4]
Make it possible to start multiple instances. At the moment it closes the previous running one

**Comment by niicojs** [comment]
I don't see this on my machine. Are you using the install or run from the source?
If you try launching it through the commande line with --enable-logging flag, could you send me the logs?

**Comment by agp89** [comment]
I'll check later today and will let you know.

**Comment by timelf123** [comment]
I didn't test with exe but with source:

`npm start` for each instance you want, change socket port if needed

**Comment by agp89** [comment]
I have the source, but i have no idea what to do with it :-D
Do i need node.js?

**Comment by niicojs** [comment]
To run from source, you have to instal nodejs current from here: https://nodejs.org/en/. Then at root of the project type "npm i && npm start".
But I don't think you need to have to go down that road. Running the exe after install just work for me with multiple instance.
However, settings is central so when you modify config the last one will be persisted.

Can I ask what you are trying to accomplish?

**Comment by agp89** [comment]
Okay, thank you very much.
Im a .Net developer and never had anything to do with nodejs yet :-/

Nah i'll go down the source road, always happy to learn something new...
but ill check the release way as well and try to reproduce my issue, guess i was just to tired yesterday :sleeping: 

I just want to see what both of the bots are doing ;-) and switching between them is not so optimal as the track is gone then.
