### ISSUE TITLE
Add evolve button

### ISSUE THREAD

**Issue by degree8th** [nicoschmitt/necrobotvisualizer#40]
Add evolve button

**Comment by niicojs** [comment]
Good idea.
Do you have an idea for an icon to use?

**Comment by degree8th** [comment]
Like Up arrow? [http://assessment-center.tbt-ua.com/img/up.png](http://assessment-center.tbt-ua.com/img/up.png)

**Comment by degree8th** [comment]
And also add onmouseover alt text tooltip on transfer and evolve buttons.

**Comment by niicojs** [comment]
I have a working version on my PC.
However, there is good chance this will only work with NecroBot. On the MobBot side there are less open to my PR it seems.
