### ISSUE TITLE
Display sniped pokemon icons

### ISSUE THREAD

**Issue by GediminasMasaitis** [nicoschmitt/necrobotvisualizer#42]
Add the icons for sniped Pokemon exactly the same way as for ones captured normally - just in the locations where they were sniped from. 

I'd love to be able to zoom out to the world map and see captured Pokemon all over the world!

**Comment by niicojs** [comment]
Yes this can be done.
Actually I wanted to do it but the info was missing on the GUI side but I've added it then.
