### ISSUE TITLE
[REQUEST] Candies

### ISSUE THREAD

**Issue by deathart** [nicoschmitt/necrobotvisualizer#43]
Hi,

Possible information for the candies needed fo evolution and total candies in the stack ?

Dsl for my english i am french

**Comment by niicojs** [comment]
Je suis Francais tu peux y aller.

**Comment by deathart** [comment]
AHHHH

Enfaite pour le système d'évolution il y aurai possiblité de savoir combien on à de bonbon et combien il en faut pour evoluer un pokémon, pour savoir combien ils nous en manque environs

**Comment by niicojs** [comment]
J'ai les infos, faut juste trouver un moyen de l'afficher proprement.
La tout de suite j'ai pas d'idée, mais je vais surtout aller me coucher. Si tu as une idée, je suis tout ouie.

**Comment by niicojs** [comment]
For english speaker:
The idea is to display candy available and candy needed for a pokemon to evolve.
I have the data, if we can find a nice way to display it this can be done.

**Comment by howcanihelp** [comment]
Maybe right bellow its name with the candy drawing and the available/needed.
ie
Dragonair
~ 14/100
where ~ stand for the candy drawing.

Not sure if this is the kind of help you're asking, though...

**Comment by niicojs** [comment]
it is :)
i'll have to do a mockup to see if it's not too much info

**Comment by howcanihelp** [comment]
![image](https://cloud.githubusercontent.com/assets/20733209/17312795/c24b7aee-5898-11e6-8981-359d686cac98.png)
Hope it helps :p

**Comment by tplk** [comment]
Can we get all the candies or only of those pokemon who are currently in backpack?
If you can get all then it'll be better to create a separate window with a table. The headings could be Pokemon (name and image), candies needed to evolve and candies available.

**Comment by Epinikion** [comment]
![necrovisualizer](https://cloud.githubusercontent.com/assets/12903229/17315625/74a32bbe-586d-11e6-9958-d4ae151fffb5.png)

with actual code i archived this, probably i find a good candy image ressource to display them instead of the label.

**Comment by niicojs** [comment]
looks good @Epinikion, could you share what you did?
