### ISSUE TITLE
[Question] Are you able to connect with the bot via web browser.

### ISSUE THREAD

**Issue by ToxicWayz** [nicoschmitt/necrobotvisualizer#46]
Hi,

I was able to get the program to work using the .exe file. I would like to know if I'm able to connect to the bot using your html files using the web browser. I've tried to edit the config.html file and refresh the index.html, but still shows connecting to bot.

The reason I'm asking is because, I would like to help with your candy problem, however I don't know how to re-package your files into an .exe for testing.

**Comment by Epinikion** [comment]
U can simply download the source and work on it with nodejs (npm i && npm start from the root folder of the project), it will run local. Theres no need to create a binary.

**Comment by niicojs** [comment]
Tell us if that works for you. It won't work in a browser (too much things unsupported in the browser).
To easily test it, install node, "npm i" to isntall "npm start" to start.
Then when you modify most files, a click in the menu "view, relead" reload the app.
