### ISSUE TITLE
Set current location marker to top layer.

### ISSUE THREAD

**Issue by degree8th** [nicoschmitt/necrobotvisualizer#51]

**Comment by niicojs** [comment]
make sens. 
Pkemon should be on top also.

I'll try, if someone find how to do it before I dig in into leaflet I'm open to it.

**Comment by niicojs** [comment]
I've done some stuff in the source tree if someone want to test

**Comment by Fawsum** [comment]
Seems to be working for the most part.
![capture1](https://cloud.githubusercontent.com/assets/3495505/17320200/22802c40-5847-11e6-814e-ba01a4096260.PNG)
![capture2](https://cloud.githubusercontent.com/assets/3495505/17320202/241844ac-5847-11e6-91f4-af9bf1ed4235.PNG)
