### ISSUE TITLE
Pop Up errors

### ISSUE THREAD

**Issue by nightah** [nicoschmitt/necrobotvisualizer#53]
Every time a Pokemon is caught an error occurs:

`[4616:0802/180049:INFO:CONSOLE(175)] "Uncaught ReferenceError: toastr is not defined", source: file:///D:/necrobotvisualizer/app/scripts/socket.js (175)`

This is running on PokeMobBot v1.1.3
With NodeJS on Windows.

**Comment by niicojs** [comment]
Seems like a library load error, maybe a network error? Could you to some more tries to see if it is consistent?

**Comment by nightah** [comment]
Every single catch, over a 1hour period is throwing the same error.

**Comment by niicojs** [comment]
could you reload or close re-rerun ?
once it is in a wrong state it would work again before a reload

**Comment by nightah** [comment]
I've tried relaunching a couple times, also because I've updated the source and had to.
Still the same issue.

**Comment by niicojs** [comment]
humm...

**Comment by niicojs** [comment]
do you see error about loading js ?
like https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js ?

also could you try opening this in a browser to see if you get the lib?
https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js

**Comment by nightah** [comment]
No errors in the console, however that link does throw a 404.

**Comment by niicojs** [comment]
there is the issue...
that is strange, do you have access to https://cdnjs.com/libraries/toastr.js/latest ?
what country are you in?

**Comment by nightah** [comment]
That link does work, and now it looks like https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js works again too.
I'll try again now.
Country: Australia.

**Comment by niicojs** [comment]
oh you're the user in australia, congrats I think you're the one that is the more far away :)
I'll try to see why cloudflare is having issue, and maybe switch away from them but there are pretty reliable most of the time

**Comment by nightah** [comment]
So I can get to the destination now however it's still consistently spitting out the same error:

`[376:0802/190535:INFO:CONSOLE(174)] "Uncaught ReferenceError: toastr is not defined", source: file:///D:/necrobotvisualizer/app/scripts/socket.js (174)`

**Comment by niicojs** [comment]
FYI I've been in touch with cloudflare and there indeed was some issues on their side. May be resolved.
Closing as it's not on my side.
