### ISSUE TITLE
Cannot view Pokemon

### ISSUE THREAD

**Issue by nightah** [nicoschmitt/necrobotvisualizer#54]
Looks like 969136320d11c863ef471067cefd5f38da28d44b has broken the ability to view Pokemon with the following error:

`[4616:0802/180237:INFO:CONSOLE(97)] "Uncaught TypeError: Cannot read property 'CandyToEvolve' of undefined", source: file:///D:/necrobotvisualizer/app/scripts/socket.js (97)`

Running with PokeMobBot v1.1.3

**Comment by niicojs** [comment]
Could you test again from source?

**Comment by nightah** [comment]
Pokemon list now works, still can't see Candy.

**Comment by niicojs** [comment]
yes, the guys from MobBot need to accept my PR first
