### ISSUE TITLE
Can you made a website interface for this nodejs app?

### ISSUE THREAD

**Issue by maithanhtan** [nicoschmitt/necrobotvisualizer#55]
Can you made a website interface for this nodejs app?

**Comment by niicojs** [comment]
what do you mean?

**Comment by maithanhtan** [comment]
i mean instead of running exe file can you made it can open on website via address http://localhost like some other node js app. So that i can access and see from other computer?

**Comment by niicojs** [comment]
not really, there is too much logic in the app itself.
but you can install the exe on another computer and modify config to access the bot remotly

**Comment by niicojs** [comment]
May be done on the way but not on short term plan
