### ISSUE TITLE
Get rid of console boxes

### ISSUE THREAD

**Issue by eslindsey** [nicoschmitt/necrobotvisualizer#56]
Can we get rid of the 2 console boxes that appear and stay there while running the app?

**Comment by niicojs** [comment]
what do you mean by console boxes? can you share a screenshot?

**Comment by eslindsey** [comment]
http://i.imgur.com/TgyRE8O.png

**Comment by niicojs** [comment]
that is not supposed to happen.
once installed to you launch it through the icon in your start menu or desktop?

**Comment by eslindsey** [comment]
Don't see an icon on my desktop or in the Start menu after running `npm install`.

**Comment by niicojs** [comment]
oh sorry your are launching it through the source code, I can see that in the screenshot.
honestly I don't get why you ge those popups. I don't.

**Comment by Epinikion** [comment]
I also dont have those popups. Tested on OS X 10.7 and Windows 7
