### ISSUE TITLE
Item count & deleting pokemon not working V1.7

### ISSUE THREAD

**Issue by li81** [nicoschmitt/necrobotvisualizer#57]
I don't think item count is working: 

http://puu.sh/qn6lF/02ba1d5e70.jpg

Also make us delete items with count ^^

**Comment by li81** [comment]
Also it's not deleting any pokemon

**Comment by niicojs** [comment]
Transfering pokemon should work if you're up to date. Good catch about the items, there is an issue.

**Comment by li81** [comment]
I don't see the transfer button either: http://puu.sh/qn6GM/c8ed1d4043.jpg

**Comment by niicojs** [comment]
when you hover a pokemon and it can be evolved you should see an icon next to the transfer (bin) button
