### ISSUE TITLE
how the hell "Evolve pokemon through the UI"

### ISSUE THREAD

**Issue by nunyaau** [nicoschmitt/necrobotvisualizer#58]
how do we evolve plaese? I can't find it anywhere.

**Comment by niicojs** [comment]
If you are up to the on the bot side:
In the UI, open pokemon list (the pokeball), then hover a pokemon and there is evolve button next to the delete button.

and please be polite (how the hell?)

**Comment by ghost** [comment]
There is no evolve button. Maybe the problem is somehow connected to the message "Candy: undefined".
![error](https://cloud.githubusercontent.com/assets/19498087/17327965/468ba2d0-58bb-11e6-8d2e-69952f10f225.jpg)

**Comment by niicojs** [comment]
Yes it is indeed connected. This feature really need the latest source on the bot side. If you run the bot with Visual Studio it should work.

**Comment by eslindsey** [comment]
Is this only for NecroBot? I'm running the development branch of PokeMobBot and I still get Candy: Undefined.

Also: it seems the delete button doesn't work with PokeMobBot, either?

**Comment by niicojs** [comment]
it will work with both, but PokeMobBot are way slower in accepting PR: https://github.com/PocketMobsters/PokeMobBot/pull/296
