### ISSUE TITLE
Candy shows up as undefined

### ISSUE THREAD

**Issue by GediminasMasaitis** [nicoschmitt/necrobotvisualizer#59]
Hey, love the new design! However there's a bug:

![image](https://cloud.githubusercontent.com/assets/7861188/17327896/44092e3a-58c3-11e6-8448-0bc03612ca28.png)

The candy count comes up as undefined, this happens for all Pokemon.

I'm using:
Pokemon bot visualizer 1.0.7
NecroBot v0.5

I'm guessing this may be an issue with the NecroBot v0.5 release not having the latest features, and needing to wait for v0.6, but I'm letting you know just in case.

**Comment by niicojs** [comment]
Yes it is exactly that :)

**Comment by Epinikion** [comment]
It works with specific pull request from @nicoschmitt (/pull/2005 for necrobot) just build necrobot with it. But was closed. Think we have a bit to wait for that feature. Also we need an additional Information how many candys are needed to evolve a specific pokemon.

Looking forward to that. :)
