### ISSUE TITLE
Wrong ordering in pokemon window

### ISSUE THREAD

**Issue by GediminasMasaitis** [nicoschmitt/necrobotvisualizer#60]
Minor bug: Sometimes, it orders the Pokemon by CP, even though the "Sort by IV" tab is selected. Changing the ordering to CP or #, and going back makes it sort by IV correctly.

EDIT: Found out exactly what caues it. Steps to reproduce:
1. Open the Pokemon window
2. Click on Sort by IV
3. Close the Pokemon window
4. Open the Pokemon window again

It now shows the Pokemon ordered by CP, even though "Sort by IV" is selected at the top.

**Comment by Algent** [comment]
I can confirm "Sort by #" is weird right now.
Its descending instead of ascending and clicking on the button again seem to toggle the order inside each number but I'm not sure what it's doing exactly.

**Comment by niicojs** [comment]
@Algent This is expected (somewhat), as I prefer sorting in a descending way.

**Comment by eslindsey** [comment]
Shouldn't it be descending for CP and IV, but ascending for #, the same way the game client does it.

**Comment by niicojs** [comment]
make sens
