### ISSUE TITLE
Transfer doesn't work

### ISSUE THREAD

**Issue by SwoleSnorlax** [nicoschmitt/necrobotvisualizer#64]
It doesn't actually transfer the pokemon.

**Comment by berenceylan** [comment]
Same

**Comment by panoszik** [comment]
same here

**Comment by niicojs** [comment]
It's because you have to be up to date on the bot side. Please add in comments in your using necro or mobbot and which version (or from source code)

**Comment by SwoleSnorlax** [comment]
Im using necro 5.0

**Comment by panoszik** [comment]
im using mob bot 1.1.3

**Comment by Epinikion** [comment]
New necrobot release, check with that now, should work :)

**Comment by xephael** [comment]
Make sure the pokemon isn't favorited. Depending on your bot settings it might be favoriting pokemon and you can't transfer those.

**Comment by niicojs** [comment]
Good catch. Did not know that.

**Comment by serginator** [comment]
Same here, mob bot 1.1.3 and transfer doesn't work

**Comment by DerekCL** [comment]
mob bot 1.1.3 pokebot visualiozer 1.0.7.

same issue

**Comment by niicojs** [comment]
Should be fixed in next release of mobbot.
