### ISSUE TITLE
[Issue] Account

### ISSUE THREAD

**Issue by li81** [nicoschmitt/necrobotvisualizer#66]

**Comment by niicojs** [comment]
not sure I understand, could you detail all step?

**Comment by Epinikion** [comment]
The visualizer just connects to the bot, so there is no account related stuff to check. Has to be an issue on the Necro-/Mobbot side.

**Comment by li81** [comment]
The account I play on has no issue with connecting to the visualizer. The one I never logged on, can't connect to the Visualizer.

**Comment by Epinikion** [comment]
Can u login with necrobot to that account? If YES 
- check config.json for the SocketPort ("WebSocketPort")
- check the settings in the visualizer (wss://IP:Port)

If NOT then it is no visualizer issue

**Comment by li81** [comment]
Bro, i'm telling you, it's not working. I can even show u on Skype.

As I said: 
The account I play on has no issue with connecting to the visualizer. The one I never logged on, can't connect to the Visualizer.

**Comment by Epinikion** [comment]
If Necrobot is working for THAT account, check the config for the right port. The visualizer is just getting the messages from the bot via Socket. Eventually u're running both at the same time or something. Otherwise explain the configuration of your setup a bit more...

**Comment by li81** [comment]
Alright, it's the issue of having multiple bots open. If you have 1 open at a time to check it out, it should be fine.

Possible look into this or close the issue @nicoschmitt

**Comment by theloser** [comment]
Can't confirm.

I have four bots and four visualizer running on four different accounts. I never logged in into one of those four accounts (using my smartphone), but the bot **and** the visualizer is working perfectly for all four accounts.

Edit: Of course I am using four different WebSocket ports to achieve this.

**Comment by li81** [comment]
Then i've got no clue tbh. Sometimes it works sometimes it doesn't

**Comment by theloser** [comment]
- Halt **all** bots (open a console window and type "taskkill /f /im necrobot.exe")
- Just start the one instance you have trouble with
- On which WebSocket port is your bot listening? (check the bot's config.json file for "WebSocketPort")
- Start the NecrobotVisualizer
- Go to settings, and check for the correct port number under "Bot Websocket"
- Click "Save"

Is it working now?

**Comment by li81** [comment]
I will just open one, if I need to check. Thx for the support though.

**Comment by theloser** [comment]
Hrmpf. Just wanted to get your setup working, but if you just create an issue and are not willing to work on this issue it's hard to find out if this is a real issue (with the program) or if it's a configuration issue on your side.

> I will just open one, if I need to check.

If this is working for you, then it's a configuration issue on your side, and we already gave you all the information you needed to fix your error ("websocketport").

I guess this issue can be closed.

> Thx for the support though.

You're welcome.

**Comment by li81** [comment]
I run 6 bots, they all have different ports. Sometimes it just doesn't want to connect to one, even after restarting both. 

But I gues the problem is on my side. What ever, closed.
