### ISSUE TITLE
Ability to upgrade pokemon using stardust

### ISSUE THREAD

**Issue by deathart** [nicoschmitt/necrobotvisualizer#68]
Bonjour,

On pourrai amélioré nos pokémon ? avec les poussière et bonbon ?

**Comment by niicojs** [comment]
au bout d'un moment va falloir sortir ton iPhone et jouer au vrai jeu :)
j'ajoute ca dans la todo list.

**Comment by deathart** [comment]
Faut je n'utilise pas d'Iphone mais un Samsung :p
Sur mon compte principal je joue au smartphone mais pour dev j'ai un autre compte de jeu ^^

**Comment by niicojs** [comment]
duplicate of #95 (I keep the english one)
