### ISSUE TITLE
Suggestion: Separate visuals for snipe jumps

### ISSUE THREAD

**Issue by Ryuichiro** [nicoschmitt/necrobotvisualizer#7]
Would be nice when we could distinguish snipe jumps from normal movement.
For example the lines could be transparent blue.

**Comment by niicojs** [comment]
First, the bot need to be updated to differentiate the events. Then I'm thinking about having to popup with list of snipes instead of the map.
Having a line from Paris to China is just wrong.

**Comment by Ryuichiro** [comment]
Maybe you could check the distance as a quick workaround?

**Comment by niicojs** [comment]
I did the PR on the bot side. Let's wait a bit to get it accepted.
