### ISSUE TITLE
[FEATURE] Pokemon Go Map Style

### ISSUE THREAD

**Issue by N0N4M3-DEV** [nicoschmitt/necrobotvisualizer#72]
Use one of these https://snazzymaps.com/explore?text=pokemon&sort=recent&tag=&color= to make visualizer map look like one in the game. Dunno if they require Google Maps API key though...

**Comment by niicojs** [comment]
Good idea but those are specific to Google Maps and I'm not using Google Maps.
By the way, you can switch maps on the upper right there is already some choices
