### ISSUE TITLE
User location is drawn on top of things interacted with

### ISSUE THREAD

**Issue by nfettinger** [nicoschmitt/necrobotvisualizer#8]
I believe the bot does not update the position to directly on top of the pokemon to catch, or the pokestop to hit. This visualizer draws it as if it were. Not sure if the issue is with this visualizer or with the bot webinterface API. Either way, it doesn't truly show the users GPS path.

**Comment by nfettinger** [comment]
FYI, I am using the GPX option to walk in a large circle around a downtown area.

**Comment by niicojs** [comment]
Yes and no. The location of the player is correct, but it can catch pokemon that are 70m away.
Location of the pokemon are not really correct but that's about to change (I did a PR into the bot).
For pokestop, it should be about right (except the fact that the icon is centered so no exactly pinned in the correct position).

**Comment by nfettinger** [comment]
Thanks for the quick update. I am using this to try to make my navigation look most humanlike.
