### ISSUE TITLE
[Request] Ability to Favorite and Un-Favorite

### ISSUE THREAD

**Issue by xephael** [nicoschmitt/necrobotvisualizer#82]
Could you add a button to favorite and unfavorite Pokemon? As well as an indicator that they are favorited?

**Comment by anonemon** [comment]
Note that there is a related issue upstream https://github.com/NECROBOTIO/NecroBot/issues/2454

**Comment by xephael** [comment]
That's totally unrelated lol. Also it's a bug on necro bot. I use pokemobbot
