### ISSUE TITLE
Shell32.dll 

### ISSUE THREAD

**Issue by Ch1l1C0nCarnag3** [nicoschmitt/necrobotvisualizer#87]
Okay, so. Tried everything I can think of. Reverted Windows. Did a full system scan. Moved Shell32.dll to the same folder as NecrobotVisualizer. Nothing works. The file will not detect Shell32.dll.

**Comment by niicojs** [comment]
Could you try downloading the install with the name **-ia32-win** in it ?

**Comment by Ch1l1C0nCarnag3** [comment]
I tried all available downloads. Both -a32-win files give me the Shell32.dll error. The others simple stop responding.

**Comment by vcxy** [comment]
I've a Shell32.dll error too, and I've Vista SP2 x86. On my Windows 7 PC it works fine.

**Comment by niicojs** [comment]
Maybe it's not compatible with Vista. Didn't know there was still those around 😉
