### ISSUE TITLE
[Suggestion] Add refresh button

### ISSUE THREAD

**Issue by marvin-bitterlich** [nicoschmitt/necrobotvisualizer#89]
Add a button to update the pokemon list in current sorting. So you don't have to close the window and open it up again and the click on the sorting.

**Comment by Corgano** [comment]
It knows when a new Pokemon is caught, instead of a button just make it auto-refresh when a new Pokemon is caught?

**Comment by marvin-bitterlich** [comment]
@Corgano this would also be done if transferring, evolving, upgrading, getting candy etc. Seems harder to do but would be better for the end user
