### ISSUE TITLE
Pokemon Level Display

### ISSUE THREAD

**Issue by xrhaomx** [nicoschmitt/necrobotvisualizer#96]
Is it possible to display the Pokemon level on the visualization, perhaps next to the name of the Pokemon.

Example:

Snorlax (20)

**Comment by Epinikion** [comment]
Just Click on the Pokemon on the Map ;) Or do u mean at the popup?

**Comment by xrhaomx** [comment]
I would like to be able to see what level it is after I have caught it in my storage list for high IV sniping purposes
