### ISSUE TITLE
Online version "Websocket connection failed" on chrome

### ISSUE THREAD

**Issue by Fawsum** [nicoschmitt/necrobotvisualizer#97]
`WebSocket connection to 'wss://localhost:14251/' failed: WebSocket opening handshake was canceled`
This is caused do to the "Allow invalid certificates for resources loaded from localhost." flag in chrome.
This can be tested/fixed by toggling the flag in chrome://flags/#allow-insecure-localhost to enabled/disabled.

**Comment by niicojs** [comment]
Could you try goiing in the config and modifying it to ws://localhost:14252 ?
(no change on the bot side, but you have to be using necrobot latest source code)

**Comment by Fawsum** [comment]
mixed content error
`Mixed Content: The page at 'https://nicoschmitt.github.io/pogo.webui/index.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://localhost:14251/'. This request has been blocked; this endpoint must be available over WSS.`

`Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.`

**Comment by xephael** [comment]
So since the online version is being hosted on a webserver, localhost wont work. To use an online version like that you'd need to use your external IP address and port forward the port.

**Comment by Fawsum** [comment]
If you don't want to enable the chrome localhost certs, yea your right

**Comment by Fawsum** [comment]
@nicoschmitt the most recent necroBot websocketinterface is suppose to accept both secure and insecure connections right? Would still raise the mixed content error I think though if visualizer hosted under an ssl cert

**Comment by xephael** [comment]
Uh no, because the webserver is trying to connect to its own localhost not yours. If it's a remote connection it has to use your external IP through a forwarded port.

**Comment by Fawsum** [comment]
@torin555 wrong. chrome://flags/#allow-insecure-localhost set to enabled. You can test yourself

**Comment by xephael** [comment]
That isn't what that does.

**Comment by Fawsum** [comment]
@torin555 wrong
![image](https://cloud.githubusercontent.com/assets/3495505/17379083/959383ec-5975-11e6-8077-529b5af3c351.png)
![image](https://cloud.githubusercontent.com/assets/3495505/17379100/b6f52edc-5975-11e6-9f38-48f9c0819aed.png)

**Comment by theloser** [comment]
@Fawsum Wether or not I set this flag to true I get this error (at the chrome debug console): "WebSocket connection to 'wss://localhost:14251/' failed: WebSocket opening handshake was canceled"

Any idea why?

Edit: The "old" (non web-ui) NecrobotVisualizer is working fine and can connect to wss://localhost:14251

**Comment by Fawsum** [comment]
@theloser make sure that when you enable chrome://flags/#allow-insecure-localhost that you restart chrome. There should be a big blue button at the bottom of the window that pops up after you alter the flag that says "Relaunch Now".
If you are still having the issue I am currently testing necrobot's end to see what errors I can produce

**Comment by theloser** [comment]
@Fawsum Wow! I didn't see the really big blue button, sorry :-)
After restarting Chrome it's working fine!
Thanks!

**Comment by Fawsum** [comment]
@theloser alright great! We are trying to get this working without having to modify chrome's security policies

**Comment by Epinikion** [comment]
it works if the bot is running locally, but my setup looks like this: Chrome on OS X and bot is running on Parallels VM with my bootcamp, so i have to listen on wss://windowsip:14252 which gives me also an certificate error handshake. So i stick to the nodejs version :)

**Comment by theloser** [comment]
Great news! But what's about multiple windows/tabs for multiple bots? All tabs are always connected to the same bot. Changing the port in one tab changes the port on all tabs, and all tabs are "switching" to the same bot.

**Comment by Epinikion** [comment]
Therefore u can use private browsing, which will give u clean configs

**Comment by xephael** [comment]
@Fawsum Well that's some magic right there... It should be completely impossible to connect remotely to anywhere at all with "localhost" since all that means is the local IP of the applications computer. It's not even referring to the external IP address of your computer it refers to the internal IP which is completely useless to anything not connected on your internet network.

Beyond even that issue is that for anything to remotely connect to any port on your router, the router needs to allow access to that port. And for anything other then some common ports such as 80 the router will block the connection unless the port is forwarded. (Keep in mind this is all before the connection even touches your computer let alone google chrome.)

Once the connection reaches your computer it needs to get past your computer's firewall. Most firewalls are set to block all uncommon external ports just like the router's firewall does, so you'd need to add an exception for the port to your computer's firewall before it would allow the connection.

After all of that the connection finally reaches chrome, where the unsecured localhost connection setting is irrelevant because the connection isn't coming from localhost, it's coming from the external webserver (in this case nicoschmitt.github.io).

So I'm completely baffled as to how it's connecting to your computer with nothing other then "localhost" (meaningless) and an unopened port.

**Comment by niicojs** [comment]
the server don't connect, everyting is client based so localhost is fine. but certificate is an issue.
@Epinikion : it should work better with ws://[name]:14252 (either wss + 14251 or ws + 14252)

**Comment by xephael** [comment]
@nicoschmitt How can it be client based when the file is on nicoschmitt.github.io? If it was a local file it would make sense, but it isn't.

**Comment by niicojs** [comment]
it is just a HTML hosted file. then the javascript executed in your brower connect to your computer.

**Comment by niicojs** [comment]
BTW, on my PC, using ws://localhost:14252 work well. but it does not seem to be like that for everyone. I don't know why.

**Comment by xephael** [comment]
Ah I see, it's using javascript. That makes a whole lot more sense. That's actually a vulnerability in javascript, which is why chrome is blocking it. Since the site forces https, you wont be able to use javascript to connect to localhost like that in chrome.

**Comment by niicojs** [comment]
you can. the thing is it's either HTTP to HTTP or HTTPS to HTTPS.
I have to find a HTTP hosting

**Comment by xephael** [comment]
Well yes, but I was saying that because most people don't have HTTPS localhost certs lol.

**Comment by niicojs** [comment]
there is one embed into necro but as it self signed you still get the error. trusting it would work

**Comment by xephael** [comment]
Yeah self signed HTTPS certificates are basically the same as no certificate. Which is good because otherwise HTTPS would be meaningless.

**Comment by niicojs** [comment]
Current guidance here: https://github.com/nicoschmitt/pogo.webui.
I'll close this for now.

**Comment by foxmanbrasil** [comment]
a had the same problem , and i found that using 
 var ws =  new WebSocket('wss://www.xxxxxxx/yyyy/');
ensted to new WebSocket('wss://xxxxxxx/yyyy/');
did the JOB, and the connection not fail after while as befor
