### ISSUE TITLE
[Feature request]Buy items and claim defender bonus

### ISSUE THREAD

**Issue by sevenzsu** [nicoschmitt/necrobotvisualizer#99]
Occasionally I need to buy items(for example: upgrade bag pack or pokemon storage) and claim defender bonus while the bot is running. Would be nice to have these features on the visulizer. Thanks

**Comment by niicojs** [comment]
I won't deal with item buying, it is really too risky to deal with real money.
Also, I don't want to handle Gym as if botter start messing with gym it will definitly ruin the game.
